### ISSUE TITLE
conventional json schema not working

### ISSUE THREAD

**Issue by Louis-Delannoy** [nfroidure/schema2dts#16]
### Expected behavior
schema of this type should work

```json
"value": {
            "description": "an array",
            "type": "array"
        },
```

### Actual behavior

we get this error `Cannot read property '$ref' of undefined`

### Steps to reproduce the behavior

try to build types with an array with no items specified

**Comment by nfroidure** [comment]
In this case, I suggest we add the Unknown type right into the `items` property. 

Putting a `{ type: 'any' }` object here https://github.com/nfroidure/schema2dts/blob/master/src/index.ts#L1045-L1047 if the array is empty should work.
