### ISSUE TITLE
NonNullable bloating the typings file

### ISSUE THREAD

**Issue by kostia1st** [nfroidure/schema2dts#33]
## Issue

I'm a gentledev I:
- [x] fully read the README recently
- [x] searched for existing issues
- [x] checked I'm up to date with the latest version of the project

### Expected behavior
There should not be any `NonNullable<>` wrappers around types that do not include nullable possibilities to begin with.
```
NonNullable<number>
NonNullable<string>
NonNullable<{ key: NonNullable<'value'> }>
```
do not make any practical sense, and just add up enormous amount of visual clutter in generated code, not to mention the bloated file size.

### Actual behavior
Contrary of the above

### Steps to reproduce the behavior
Generate typings against virtually any OpenAPI out there.

**Comment by nfroidure** [comment]
@kostia1st feel free to create a PR, it should sit around there: https://github.com/nfroidure/schema2dts/blob/main/src/index.ts#L1062C44-L1062C57

**Comment by nfroidure** [comment]
@kostia1st I finally gave it a lil try, feel free to review: https://github.com/nfroidure/schema2dts/pull/34

**Comment by kostia1st** [comment]
That looks great!

**Comment by nfroidure** [comment]
Just published the v6 then.
